version: '3.1'

services:
    mongo:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports:
          - "27017:27017"
        networks:
          - net
            
    mongo-test:
        image: mongo:latest
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=cr34t1v3dr1v3r
          - MONGO_INITDB_DATABASE=user-microservice
        ports:
          - "27018:27017"
        volumes:
          - ./volumes/mongo-test/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        networks:
          - net
      
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - "8081:8081"
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: cr34t1v3dr1v3r
        restart: on-failure
        depends_on:
          - mongo
        networks:
          - net
          
networks:
    net:
        driver: bridge