version: '3.1'

services:
    mongo:
        image: mongo:latest
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=cr34t1v3dr1v3r
          - MONGO_INITDB_DATABASE=user-microservice
        ports:
          - "27017:27017"
        volumes:
          - ./volumes/mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        networks:
          - lognet
            
    mongo-test:
        image: mongo:latest
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=cr34t1v3dr1v3r
          - MONGO_INITDB_DATABASE=user-microservice
        ports:
          - "27018:27017"
        volumes:
          - ./volumes/mongo-test/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        networks:
          - lognet
      
    mongo-express:
        image: mongo-express
        restart: always
        ports:
          - "8081:8081"
        environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: root
          ME_CONFIG_MONGODB_ADMINPASSWORD: cr34t1v3dr1v3r
        restart: on-failure
        depends_on:
          - mongo
        networks:
          - lognet
        
    user-microservice:
        restart: on-failure
        build: .
        ports:
          - "8091:8091"
        environment:
            SPRING_DATA_MONGODB_URI: mongodb://creativedriver:cr34t1v3dr1v3r@mongo:27017/user-microservice
        depends_on:
          - mongo
        networks:
          - lognet
          
networks:
    lognet:
        driver: bridge