apiVersion: v1
kind: Service
metadata:
    name: mongo
    labels:
        component: mongo
spec:
    ports:
        - port: 27017
          targetPort: 27017
          nodePort: 31516
          protocol: TCP
    selector:
        component: mongo 
---        
apiVersion: apps/v1
kind: Deployment
metadata:
    name: mongo
spec:
    replicas: 1
    selector:
        matchLabels:
            component: mongo
    template:
        metadata:
            labels:
                component: mongo
        spec:
            containers:
            - name: mongo
              image: tomasoares/mongo
              ports:
                - containerPort: 27017